Updated Community Section in Readme
layer5io/meshery-istio pull request #226
Opened 2021-06-04 09:16 UTC by DARK-art108

**Description**

Updated Community Section in Readme

This PR fixes #211 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2021-06-04 09:30 UTC, DARK-art108 commented
Hello @leecalcote ,take a look at the PR and consider the commit : `21e19e2c37a50b9cd4408663f69749c2f1a6f415`

2021-06-04 14:42 UTC, DARK-art108 commented
@leecalcote Please take a look at the PR :)

2021-06-07 22:20 UTC, leecalcote commented
Thank you, @DARK-art108

2021-06-07 22:21 UTC, leecalcote requested changes

2021-06-07 22:21 UTC, leecalcote commented on README.md
> +✔️ <em><strong>To Access the Community Drive</strong></em>, fill <a href="https://layer5.io/newcomer">Community Member Form</a>.<br />
lowercase "access"

2021-06-08 05:58 UTC, DARK-art108 commented on README.md
> +✔️ <em><strong>To Access the Community Drive</strong></em>, fill <a href="https://layer5.io/newcomer">Community Member Form</a>.<br />
Done @leecalcote Added Suggested Changes!

2021-06-08 11:21 UTC, leecalcote approved these changes
Thanks, @DARK-art108 👍

2021-06-08 11:21 UTC, merged